name: peacoat
favicon: null
layout_spectrum: 0.35640045488253236
typography_spectrum: 0.5811369814909995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10580363404005766
  lightness: 0.24780887831002474
  saturation: 0.12886142451316118
  rhythmicContrast: 0.7365268007852137
purpose: []
